travis:
  secure:
    BINSTAR_TOKEN: lj/nF6kltGVUNUIP13nv9l/oLvbIMjtVk64dVERuR7LcQuAATNd7t1r6rSSn/Dv2dffdfkLNob815jME5E/Lp8zIgsWkUyUabgS3/hVsrmbWXbYAk6pvLC+NDtGFwnejUggY335oGTLCHcQnQA4h92QDI3bICFHKbo5VpMZh4FaXRMtbDhZtCpbC2mljg1a6O6+gXtZGlQyFCuQioHbkyv7WLcATGi365gGVlZfYaWiqj9vpoWH6CuDbOl7j6eKyTTKCoWDDc5mAXMYtL5rqyMXTjmpOmDjbSsz9KLBNzw2II/MjgJChC19hDvH/4CzZJwnQ/ZfPVnxq4UBx/hUaHgT3E/smNVwDdFdlBjlVahiYqM4NFSYOtEndVFuBA8od50zd4lTEbzJX2sKZzQxoJfZkk7EypnG936lqXdE3nHhlzWZdc++UVT4ELIDArelwlFVNj86KWbRQwlGi4rJqUaCh6vXIWAHKE4U9mK2pA/pOG1DeIXaTMkgkP8p+EGfWk9y3hA6kIFH8AukGOpU3y1CNcJCxyHMgc56KGvwEQJi99FgjnijTHIhP4laVA8VZiOKhhOykqvsgTXa4YNzqT+K7VRqzASS+3crdRcXIQGgicrCoa94CGatHdhYkGtsOrfnc91ZKlMGa0+5OlKmzaBlphGQ4rIIJWh3hLBwZ6Pk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
